### ISSUE TITLE
A problem about the bound

### ISSUE THREAD

**Issue by slongle** [mitsuba-renderer/mitsuba2-vdb-converter#1]
Hi, on line 58, the bound's dimension is not the true bound in index space , because the bound is not always begin at (0,0,0). I think it should be changed like this.

    auto bbox_dim = grid->evalActiveVoxelDim();
    auto bbox = grid->evalActiveVoxelBoundingBox();

    auto ws_min = grid->indexToWorld(bbox.min());
    auto ws_max = grid->indexToWorld(bbox.max() - openvdb::Vec3R(1,1,1));

    for (int k = bbox.min().z(); k < bbox.max().z(); ++k) {
        for (int j = bbox.min().y(); j < bbox.max().y(); ++j) {
            for (int i = bbox.min().x(); i < bbox.max().x(); ++i) {
                ...
            }
        }
    }

    write(output_file, (int32_t)1); // type
    write(output_file, (int32_t)bbox_dim.x() - 1);
    write(output_file, (int32_t)bbox_dim.y() - 1);
    write(output_file, (int32_t)bbox_dim.z() - 1);
    write(output_file, (int32_t)1); // #n channels   

For example, in the disney cloud dataset, the wdas_cloud_sixteenth.vdb, 
bbox_dim = [126, 86, 154]
bbox.min() = [-66, -21, -90]
bbox.max() = [59, 64, 63]

If you think it's ok, I can make a PR for you.

**Comment by dvicini** [comment]
Hi, 

That makes sense, thanks for looking into it. Could you please make a pull request with your changes?

Delio

**Comment by dvicini** [comment]
Fixed by https://github.com/mitsuba-renderer/mitsuba2-vdb-converter/pull/2
